# Generated by Django 5.2.4 on 2025-07-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obstaculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('bache', 'Bache'), ('poste', 'Poste'), ('muro', 'Muro'), ('vehiculo_mal_estacionado', 'Vehículo Mal Estacionado'), ('rampa', 'Rampa Elevada'), ('escalera', 'Escalera'), ('cruce_peligroso', 'Cruce Peligroso'), ('vereda_estrecha', 'Vereda Estrecha'), ('zona_trafico_intenso', 'Zona de Tráfico Intenso'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Obstáculo',
                'verbose_name_plural': 'Obstáculos',
            },
        ),
    ]
