# Generated by Django 5.2.4 on 2025-07-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection_simulator', '0002_ruta_puntoruta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PuntoRuta',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
    ]
