# Generated by Django 5.2.4 on 2025-07-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_simulator', '0003_delete_puntoruta_delete_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('coordenadas', models.JSONField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
